import { SubjectMeta, Topic, Flashcard, Question, GlossaryTerm } from '@/types/study';
import { tokens } from '@/design-system/tokens';

export const topics: Topic[] = [
  {
    id: 'sia1-eia',
    subjectId: 'sia1',
    title: 'Enterprise Information Architecture (EIA)',
    order: 1,
    estimatedMinutes: 45,
    professorMode: {
      eli5: 'EIA is a city planner\'s master blueprint. It makes sure the roads (networks), buildings (applications), and water pipes (data) connect properly so the city works as one place instead of isolated neighbourhoods.',
      deepDive: 'Enterprise Architecture (EA) links an organisation\'s business mission and strategy to its IT strategy, and is documented using multiple architectural models that must adapt to changing requirements and technology. Enterprise Information Architecture (EIA) is the information-centred viewpoint inside EA: the requirements, principles, and models that describe the current state, the target state, and the guidance needed to share information assets flexibly. Four methodologies dominate the field. TOGAF divides EA into business, application, data, and technical architecture. The Zachman Framework crosses six descriptive foci (data, function, network, people, time, motivation) with six player perspectives, producing a 36-cell grid. The Federal Enterprise Architecture uses five reference models: business, components, technical, data, and performance. The Gartner methodology brings business owners, information specialists, and technology implementers together. A well-defined EIA gains transparency by keeping information independent of any single application, considers enterprise-wide requirements, and exposes inconsistencies, conflicts, overlaps, and gaps. Its primary goal is reducing complexity so the organisation can absorb change. Crucially, EIA does not target every byte in the enterprise—only the information assets with enterprise significance that are needed to achieve effective business change.',
      analogy: 'Without EIA, a company\'s software is a group of people speaking different languages in a noisy room. EIA introduces a shared vocabulary and a rule about taking turns.',
      visualAidType: 'diagram',
      visualAidData: {
        type: 'eia-hub-spoke',
        nodes: ['CRM', 'ERP', 'Billing', 'ESB Hub'],
      },
    },
    relatedTermIds: ['term-ea', 'term-eia', 'term-togaf', 'term-zachman', 'term-silo'],
    tags: ['architecture', 'eia', 'integration'],
  },
  {
    id: 'sia1-governance',
    subjectId: 'sia1',
    title: 'IT Governance and Risk',
    order: 2,
    estimatedMinutes: 50,
    professorMode: {
      eli5: 'Governance is the steering wheel, not the engine. The board decides where IT should go and checks that it got there; management does the driving.',
      deepDive: 'Governance of Enterprise IT (GEIT) is the responsibility of the board of directors and executive management. It exists to answer two questions: is IT delivering value to the business, and is IT-related risk being managed? The framework answers them through three broad processes—IT resource management (an up-to-date inventory of IT resources and their risk), performance measurement (indicators tuned for value delivery, where deviation is an early risk signal), and compliance management (legal, regulatory, policy, and contractual requirements). Two committees are commonly confused. The IT strategy committee advises the board on strategic direction, value, risk, and future capability. The IT steering committee is a management group that reviews plans against corporate objectives, approves major acquisitions within board limits, prioritises projects and budgets, approves sourcing strategies, and allocates resources. Risk management identifies vulnerabilities and threats to information resources and treats them in one of four ways: avoid, mitigate, transfer, or accept. Whatever remains after controls is residual risk, and accepting it is an explicit management decision. Segregation of duties separates authorisation, custody of assets, and recording of transactions; where that separation is impractical, compensating controls such as audit trails, reconciliation, exception reporting, and independent review take its place.',
      analogy: 'The board is the ship\'s owner setting the destination and reading the instruments; the captain and crew are management. Owners who never read the instruments discover problems only when the ship is aground.',
      visualAidType: 'table',
      visualAidData: {
        headers: ['Risk treatment', 'What you do', 'Example'],
        rows: [
          ['Avoid', 'Stop the risky activity.', 'Retire a legacy service that cannot be secured economically.'],
          ['Mitigate', 'Reduce likelihood or impact.', 'Add multifactor authentication and monitoring.'],
          ['Transfer', 'Shift part of the impact elsewhere.', 'Buy cyber insurance.'],
          ['Accept', 'Knowingly retain the residual risk.', 'Document a low-impact risk that costs more to fix than to bear.'],
        ],
      },
    },
    relatedTermIds: ['term-geit', 'term-residual-risk', 'term-sod', 'term-steering-committee'],
    tags: ['governance', 'risk', 'controls'],
  },
  {
    id: 'sia1-data-modelling',
    subjectId: 'sia1',
    title: 'Information and Data Modelling',
    order: 3,
    estimatedMinutes: 40,
    professorMode: {
      eli5: 'Data is a building block that means the same thing everywhere. Information is data placed in a context so a person or a process can act on it.',
      deepDive: 'The information and data layer of an enterprise architecture meta model separates two ideas that beginners routinely merge. Data has the same value and meaning regardless of the context in which it is used—Customer, Product, Currency, Invoice. Information is data in context: the report a BI tool produces, the view an application presents, the message two applications exchange. Applications store and manage data; business processes consume information. The layer is split into three views. The conceptual view defines the what: information architecture objectives, principles, and drivers, plus information concepts (Cost, Stock Volume) and data subjects (Customer, Product, Site, Employee). These provide the semantic grounding for everything below. The logical view defines the how: information views refine a concept for a particular audience (Customer::Marketing View), information view attributes specify derivations, data objects group data attributes, and representations bind them to a technology such as an Oracle HR database or a payroll spreadsheet. The physical view captures the where: an information store is a deployed representation with a role such as Production, Development, or Test, and a physical data object is the data actually sitting in that store. A useful rule of thumb is that a healthy conceptual model has many more information concepts than data subjects.',
      analogy: 'The word "42" is data. "42 degrees Celsius, patient temperature, taken now" is information—the context is what makes it worth acting on.',
      visualAidType: 'table',
      visualAidData: {
        headers: ['Layer', 'Question', 'Example construct'],
        rows: [
          ['Conceptual', 'What matters?', 'Information Concept, Data Subject'],
          ['Logical', 'How is it represented?', 'Information View, Data Object'],
          ['Physical', 'Where is it deployed?', 'Information Store, Physical Data Object'],
        ],
      },
    },
    relatedTermIds: ['term-information', 'term-data', 'term-data-subject', 'term-information-store'],
    tags: ['modelling', 'data', 'information'],
  },
  {
    id: 'sia1-soa',
    subjectId: 'sia1',
    title: 'Service-Oriented Architecture (SOA)',
    order: 4,
    estimatedMinutes: 45,
    professorMode: {
      eli5: 'SOA builds an application out of separate services that each do one clear job and agree on how to talk. Anything that follows the agreed contract can reuse them.',
      deepDive: 'Service-Oriented Architecture is a software design style in which application components provide services to other components through communication protocols such as SOAP. A service is a clear, independent function that can exchange data with other services without depending on their internals; it uses a loosely coupled, message-based design. Services fall into families. Infrastructure services handle non-functional work—logging, authentication, security—and subdivide into communication services (message transport) and utility services (reusable technical capabilities such as event logging and notification). Business services perform business functions and subdivide into activity, process, entity, and capability services. Application services expose a dedicated user interface that invokes other services. Enterprise services implement functionality defined by the business services, drawing on infrastructure and application services. Nine design principles keep services reusable: standardised service contract, loose coupling, service abstraction, reusability, autonomy, statelessness, discoverability, composability, and interoperability. Three participants make discovery work: the service provider creates a service and publishes its description; the service registry (also called the broker or repository) holds those offers; the service consumer finds an entry, binds to the provider, and invokes the service. The reference framework has five horizontal layers—consumer interface, business process, services, service component, and operational systems.',
      analogy: 'A restaurant kitchen with stations. The grill station does not care who ordered the steak; it only needs the ticket in the agreed format.',
      visualAidType: 'table',
      visualAidData: {
        headers: ['SOA principle', 'Meaning', 'What breaks without it'],
        rows: [
          ['Standardised contract', 'Every service publishes a description.', 'Consumers guess at the interface.'],
          ['Loose coupling', 'Services minimise dependencies.', 'One failure stops the client application.'],
          ['Statelessness', 'No data is kept between requests.', 'Only one instance can serve a caller.'],
          ['Discoverability', 'Services can be found in a registry.', 'Addresses get hard-coded everywhere.'],
        ],
      },
    },
    relatedTermIds: ['term-soa', 'term-service', 'term-esb', 'term-service-registry', 'term-loose-coupling'],
    tags: ['architecture', 'soa', 'services'],
  },
  {
    id: 'sia1-microservices',
    subjectId: 'sia1',
    title: 'Microservice Architecture',
    order: 5,
    estimatedMinutes: 45,
    professorMode: {
      eli5: 'Instead of one huge program, you build many small ones that work together. Each is deployed and scaled on its own, so changing one does not force you to redeploy everything.',
      deepDive: 'The microservices architecture style develops small services that each run in their own process, enabling continuous delivery of large, complex applications and letting an organisation evolve its technology stack. It contrasts with a monolithic application, which is developed and deployed all in one piece. Microservices split into infrastructure services (security, logging, auditing) and functional services (business operations). Design traits include a distributed architecture where services communicate through an API gateway over REST or RPC, separately deployed components so a change in one does not force redeployment of the others, service components that locate each other through service discovery, and bounded contexts that encapsulate one domain and define its integration with others. The defining characteristics are: small in size, messaging enabled, bounded by contexts, autonomously developed, independently deployable, decentralised, and built and released with automated processes. Because microservices are isolated, they need an inter-process communication mechanism. The supporting components are clients, an identity provider that authenticates and issues tokens, an API gateway that handles requests from many clients, static content, service discovery, a content delivery network, and remote services. The payoff is targeted scaling and deployment: only the component under load is scaled, and only the changed service is deployed. Best practices are independent teams, automate everything, build for resilience, simplify maintenance with documentation, and give teams flexibility.',
      analogy: 'SOA shares one kitchen and a head waiter. Microservices give every chef their own food truck; they coordinate by calling out the window.',
      visualAidType: 'table',
      visualAidData: {
        headers: ['Concern', 'SOA', 'Microservices'],
        rows: [
          ['Coordination', 'Often a centralised bus.', 'Choreography through lightweight APIs.'],
          ['Granularity', 'Coarse-grained services.', 'Fine-grained services.'],
          ['Deployment', 'Larger shared release units.', 'Independently deployable services.'],
          ['Scaling', 'Scale the shared platform.', 'Scale only the loaded component.'],
        ],
      },
    },
    relatedTermIds: ['term-microservices', 'term-monolith', 'term-api-gateway', 'term-bounded-context'],
    tags: ['architecture', 'microservices', 'scalability'],
  },
  {
    id: 'sia1-data-representation',
    subjectId: 'sia1',
    title: 'Data Representation: XML and JSON',
    order: 6,
    estimatedMinutes: 40,
    professorMode: {
      eli5: 'XML and JSON are two ways of writing data down so that any program can read it. XML lets you invent tags; JSON writes name-value pairs and lists.',
      deepDive: 'XML is a hierarchical, human-readable markup language designed to carry data rather than display it, and its tags are defined by the author rather than predefined. It contains two kinds of items: elements, which nest, may repeat, and whose order matters, and attributes, which are named values that appear at most once per element and whose order does not matter. Any legal XML document is parsable without knowing what the tags mean, provided it is well-formed: a prolog declaring version and encoding, exactly one root element, a closing tag for every open tag (or the empty-element shortcut), quoted attribute values, correct nesting, and case-sensitive names. JSON specifies objects as name-value pairs. A JSON instance contains a single value, which may be an object, array, number, string, true, false, or null. Objects wrap string-colon-value pairs in braces; arrays wrap ordered values in brackets. Keys must be unique because parser behaviour on duplicates is unpredictable, and many implementations report only the last pair. Strings are double-quoted, must escape the quotation mark, backslash, and control characters U+0000 to U+001F, and may not span lines—the newline is written as the two-symbol escape sequence. JSON has no comment syntax. Both are hierarchical, language independent, and used by Ajax; JSON is less verbose and has native arrays, while XML can be validated and normalises newlines. Both have schema languages written in themselves: XML Schema in XML, JSON Schema in JSON.',
      analogy: 'XML is a labelled filing cabinet: every folder is named and can hold folders. JSON is a shopping list with headings—shorter to write, just as easy to follow.',
      visualAidType: 'table',
      visualAidData: {
        headers: ['Aspect', 'XML', 'JSON'],
        rows: [
          ['Schema language', 'DTD and XML Schema, written in XML.', 'JSON Schema, written in JSON.'],
          ['Lists', 'Repeated elements.', 'Native arrays.'],
          ['Comments', 'Supported.', 'Not allowed.'],
          ['Newlines', 'Normalised by the parser to LF.', 'Multi-line strings forbidden; use the escape.'],
        ],
      },
    },
    relatedTermIds: ['term-xml', 'term-json', 'term-well-formed', 'term-json-schema'],
    tags: ['data', 'xml', 'json'],
  },
  {
    id: 'sia1-web-services',
    subjectId: 'sia1',
    title: 'Web Services: SOAP, WSDL, and UDDI',
    order: 7,
    estimatedMinutes: 45,
    professorMode: {
      eli5: 'A web service lets two programs cooperate even when they run on different systems. SOAP is the envelope, WSDL is the instruction sheet, UDDI is the directory.',
      deepDive: 'A web service is a software system supporting interoperable machine-to-machine interaction: more than one application is involved, and they cooperate without sharing a platform, operating system, or programming language. Web services are delivered by three protocols built on XML and HTTP. SOAP is a messaging framework specifying message format, message processing, and transport. A SOAP message is an Envelope containing an optional Header and a mandatory Body; errors are reported as a fault inside the Body. Messages travel one way along a path of nodes—initial sender, intermediaries, ultimate receiver—so request and response are treated as two messages under a message exchange pattern. Header blocks are targeted at a SOAP role; the node in that role must perform the implied processing and delete the block before relaying the message onward, which is how authentication and routing are layered in. Over HTTP, a 2xx status indicates success while 400 and 500 accompany a SOAP fault. WSDL is an XML grammar describing network services as collections of endpoints. Its abstract half defines types, messages, operations, and port types; its concrete half defines a binding (a protocol and data format for a port type), a port (a binding plus a network address), and a service (a collection of related ports). Separating the two halves lets the same abstract definitions be reused across protocols. UDDI provides a searchable repository of service descriptions so clients can discover services dynamically.',
      analogy: 'SOAP is the envelope and the postal rules, WSDL is the form telling you exactly what to write and where to send it, and UDDI is the phone book.',
      visualAidType: 'table',
      visualAidData: {
        headers: ['Protocol', 'Answers', 'Carries'],
        rows: [
          ['SOAP', 'How is the message packaged and processed?', 'An XML envelope with header and body.'],
          ['WSDL', 'What can the service do and where is it?', 'Types, messages, operations, bindings, ports.'],
          ['UDDI', 'Which services exist at all?', 'A searchable registry of descriptions.'],
        ],
      },
    },
    relatedTermIds: ['term-web-service', 'term-soap', 'term-wsdl', 'term-uddi', 'term-rpc'],
    tags: ['web-services', 'soap', 'wsdl'],
  },
  {
    id: 'sia1-eai',
    subjectId: 'sia1',
    title: 'Enterprise Application Integration (EAI)',
    order: 8,
    estimatedMinutes: 45,
    professorMode: {
      eli5: 'When applications cannot talk, people retype the same data in several systems. EAI connects them so information flows automatically.',
      deepDive: 'Enterprise Application Integration is the task of uniting the databases and workflows associated with business applications so that the business uses information consistently and a change made in one application is correctly reflected in the others. The problem it solves is the information silo: data captured in one application must be re-entered elsewhere, modifications are not propagated, and users search manually for data that already exists—producing poor access to information, administrative delays, and slower processes. There is no standardised model, so five approaches emerged. Point-to-point integration scripts extract, reformat, and send data between two applications; effective for a handful of systems, unmanageable as dependencies multiply. Hub-and-spoke integration puts a central hub in charge of capture, reformatting, and routing, though developers still route data manually at runtime. Bus integration evolves that model, using a defined set of standards to govern flow without human interference. Middleware acts as a hidden translation layer between application user interfaces and operating systems. Microservices, the current standard for cloud-deployed enterprise applications, capture data from each deployed service and route it through APIs. Integration also happens at four depths. Data-level EAI moves and reformats data between data stores and is cheapest because application code is untouched. Application interface level EAI uses interfaces exposed by packaged applications such as SAP or PeopleSoft, typically through message brokers. Method level EAI shares business logic through distributed objects, application servers, and TP monitors. User interface level EAI drives the application through its screens and is used only when nothing else is exposed.',
      analogy: 'Five departments each keeping their own address book. EAI is the rule that when one book changes, the others change too—without anyone retyping.',
      visualAidType: 'table',
      visualAidData: {
        headers: ['EAI type', 'Integration point', 'Relative cost'],
        rows: [
          ['Data level', 'The database.', 'Lowest—no application changes.'],
          ['Application interface', 'Published application interfaces.', 'Moderate—limited by exposed features.'],
          ['Method level', 'Shared business logic.', 'Higher—robust technologies required.'],
          ['User interface', 'The application screen.', 'Fragile—used when nothing else exists.'],
        ],
      },
    },
    relatedTermIds: ['term-eai', 'term-silo', 'term-point-to-point', 'term-hub-spoke', 'term-message-broker'],
    tags: ['integration', 'eai', 'enterprise'],
  },
  {
    id: 'sia1-middleware',
    subjectId: 'sia1',
    title: 'Middleware and Messaging',
    order: 9,
    estimatedMinutes: 45,
    professorMode: {
      eli5: 'Middleware is the software in the middle. It hides how complicated the network and the back end really are and gives applications one simple way to ask for what they need.',
      deepDive: 'Middleware is the software between application programs and the operating system and base networking. It provides higher-level distributed computing capabilities and a set of interfaces to reach them, bridging the gap between low-level operating-system communication and programming-language abstractions, and hiding the complexity and heterogeneity of a distributed system. The name comes from its position: it sits between client-side requests on the front end and the back-end resources being requested—databases, message queues, NoSQL stores, and file servers—and provides a messaging service such as SOAP, REST, or JSON for applications to transfer data. It carries four responsibilities. It manages connectivity, for example by creating a connection pool for fast access to a popular database, or connections to message queues and cloud resources. It implements logic based on the request, such as tailoring queries to a browser\'s language header or prioritising results near the client\'s location. It handles concurrent processing, load balancing, and transaction management, scaling vertically and horizontally to spread requests over servers, virtual machines, or availability zones, and resolving conflicts when two clients update the same resource. Finally it secures access, challenging clients for a secure connection using SSL and authentication before returning data over an encrypted channel. Middleware is grouped into two categories—enterprise application integration middleware and platform middleware—and into types including messaging, object or ORB, remote procedure call, database, transactional, content-centric, and embedded middleware.',
      analogy: 'Middleware is the postal service. You drop the letter in the box; you do not need to know whether the recipient is home right now.',
      visualAidType: 'table',
      visualAidData: {
        headers: ['Middleware type', 'Best for', 'Example use'],
        rows: [
          ['Messaging', 'Events between distributed services.', 'Order placed → billing and shipping notified.'],
          ['Object / RPC', 'Calling remote components.', 'One application invoking another\'s methods.'],
          ['Database', 'Direct data access.', 'SQL access to a shared customer store.'],
          ['Transactional', 'Multi-step consistency.', 'Transaction process monitoring across phases.'],
        ],
      },
    },
    relatedTermIds: ['term-middleware', 'term-mom', 'term-pubsub', 'term-connection-pool'],
    tags: ['middleware', 'messaging', 'asynchronous'],
  },
  {
    id: 'sia1-cloud',
    subjectId: 'sia1',
    title: 'Cloud Computing',
    order: 10,
    estimatedMinutes: 45,
    professorMode: {
      eli5: 'Cloud computing means using someone else\'s computers over the internet instead of buying your own. You ask for what you need, use it, and pay only for what you used.',
      deepDive: 'Cloud computing is a model for enabling convenient, on-demand network access to a shared pool of configurable computing resources—networks, servers, storage, applications, services—that can be rapidly provisioned and released with minimal management effort or service provider interaction. Five essential characteristics define it: on-demand self-service, broad network access, resource pooling with location independence, rapid elasticity, and measured service under a pay-per-use model. Three traits are common to every vendor: the back end is completely managed by the provider, the user pays only for services used, and services are scalable. Virtualisation is the enabling technology, letting a provider pool resources and divide them among multiple clients in a multi-tenant environment. Architecturally, the front end is the client\'s network and applications reaching the cloud through an interface such as a browser; the back end is the cloud itself—servers, storage, and the built-in security, traffic control, and middleware protocols that let devices communicate. There are three service models: Infrastructure as a Service, Platform as a Service, and Software as a Service. There are four deployment models: public (open to the general public, pay-as-you-go, shared infrastructure pool), private (exclusive to one organisation, on or off premises), community (shared among organisations with similar missions, security requirements, or policies), and hybrid (critical activities on the private side, non-critical on the public side). Five actors take part: cloud consumer, cloud provider, cloud auditor, cloud broker, and cloud carrier. The network is decisive—no network means no cloud.',
      analogy: 'Electricity from the grid. You do not buy a generator; you plug in, use what you need, and pay for the metered amount.',
      visualAidType: 'table',
      visualAidData: {
        headers: ['Deployment model', 'Who may use it', 'Typical reason'],
        rows: [
          ['Public', 'The general public.', 'Lowest cost and fastest start.'],
          ['Private', 'One organisation.', 'Higher security and control.'],
          ['Community', 'Organisations with shared requirements.', 'Shared mission or regulation.'],
          ['Hybrid', 'A mix of public and private.', 'Keep critical work private, burst the rest.'],
        ],
      },
    },
    relatedTermIds: ['term-cloud', 'term-iaas', 'term-paas', 'term-saas', 'term-hybrid-cloud', 'term-multi-tenancy'],
    tags: ['cloud', 'deployment', 'service-models'],
  },
];

export const subjectMeta: SubjectMeta = {
  id: 'sia1',
  title: 'Systems Integration & Architecture 1',
  shortTitle: 'Sys Integration 1',
  description:
    'Enterprise information architecture, IT governance, data modelling, service and microservice architecture, data representation, web services, application integration, middleware, and cloud computing.',
  accent: tokens.colors.subject.sia1,
  // Derived from the topic list so the dashboard can never advertise a stale count.
  topicCount: topics.length,
  estimatedHours: Math.round(
    topics.reduce((total, topic) => total + topic.estimatedMinutes, 0) / 60
  ),
};

export const glossary: GlossaryTerm[] = [
  { id: 'term-ea', term: 'Enterprise Architecture', definition: 'A framework linking business mission and strategy to IT strategy, documented with multiple architectural models that adapt to changing requirements.', topicIds: ['sia1-eia'] },
  { id: 'term-eia', term: 'EIA', definition: 'Enterprise Information Architecture. The requirements, principles, and models describing current state, future state, and the guidance needed to share information assets.', topicIds: ['sia1-eia'] },
  { id: 'term-togaf', term: 'TOGAF', definition: 'An enterprise architecture framework that divides EA into business, application, data, and technical architecture.', topicIds: ['sia1-eia'] },
  { id: 'term-zachman', term: 'Zachman Framework', definition: 'A 36-cell grid crossing six descriptive foci (data, function, network, people, time, motivation) with six player perspectives.', topicIds: ['sia1-eia'] },
  { id: 'term-silo', term: 'Information Silo', definition: 'An isolated data system incapable of reciprocal operation with the other systems that need its information.', topicIds: ['sia1-eia', 'sia1-eai'] },
  { id: 'term-geit', term: 'GEIT', definition: 'Governance of Enterprise IT. The board and executive system that directs IT so it delivers value and keeps IT-related risk acceptable.', topicIds: ['sia1-governance'] },
  { id: 'term-residual-risk', term: 'Residual Risk', definition: 'The risk that remains after existing or planned controls are applied; accepting it is an explicit management decision.', topicIds: ['sia1-governance'] },
  { id: 'term-sod', term: 'Segregation of Duties', definition: 'Dividing authorisation, custody of assets, and recording of transactions so one person cannot control an entire sensitive transaction.', topicIds: ['sia1-governance'] },
  { id: 'term-steering-committee', term: 'IT Steering Committee', definition: 'A management group that reviews IS plans against corporate objectives, approves major acquisitions, prioritises projects, and allocates resources.', topicIds: ['sia1-governance'] },
  { id: 'term-information', term: 'Information', definition: 'Data placed in context so it becomes meaningful to a person, application, or business process.', topicIds: ['sia1-data-modelling'] },
  { id: 'term-data', term: 'Data', definition: 'A building block whose value and meaning stay the same regardless of the context in which it is used.', topicIds: ['sia1-data-modelling'] },
  { id: 'term-data-subject', term: 'Data Subject', definition: 'A high-level conceptual kind of data used to deliver information, such as Customer, Product, Site, or Employee.', topicIds: ['sia1-data-modelling'] },
  { id: 'term-information-store', term: 'Information Store', definition: 'A physical deployment of an information representation, tagged with its role such as Production, Development, or Test.', topicIds: ['sia1-data-modelling'] },
  { id: 'term-soa', term: 'SOA', definition: 'Service-Oriented Architecture. A design style in which application components provide services to other components through agreed communication protocols.', topicIds: ['sia1-soa'] },
  { id: 'term-service', term: 'Service', definition: 'A clear, independent function that describes a piece of functionality and can exchange data with other services.', topicIds: ['sia1-soa'] },
  { id: 'term-esb', term: 'ESB', definition: 'Enterprise Service Bus. Shared messaging infrastructure through which services expose themselves and exchange messages.', topicIds: ['sia1-soa', 'sia1-eai'] },
  { id: 'term-service-registry', term: 'Service Registry', definition: 'The broker or repository holding published service offers so consumers can find and bind to a provider.', topicIds: ['sia1-soa'] },
  { id: 'term-loose-coupling', term: 'Loose Coupling', definition: 'The principle that services minimise dependencies, so one service failing does not stop the client application.', topicIds: ['sia1-soa'] },
  { id: 'term-microservices', term: 'Microservices', definition: 'An architectural style structuring an application as small services that each run in their own process and deploy independently.', topicIds: ['sia1-microservices'] },
  { id: 'term-monolith', term: 'Monolithic Application', definition: 'An application developed and deployed as one indivisible piece.', topicIds: ['sia1-microservices'] },
  { id: 'term-api-gateway', term: 'API Gateway', definition: 'The component that handles requests from various clients and routes them into the microservice system.', topicIds: ['sia1-microservices'] },
  { id: 'term-bounded-context', term: 'Bounded Context', definition: 'A boundary encapsulating the details of a single domain and defining how it integrates with other domains.', topicIds: ['sia1-microservices'] },
  { id: 'term-xml', term: 'XML', definition: 'Extensible Markup Language. A hierarchical, self-descriptive markup language designed to carry data, with author-defined tags.', topicIds: ['sia1-data-representation'] },
  { id: 'term-json', term: 'JSON', definition: 'JavaScript Object Notation. A mostly language-independent way of specifying objects as name-value pairs.', topicIds: ['sia1-data-representation'] },
  { id: 'term-well-formed', term: 'Well-Formed XML', definition: 'XML that follows the syntax rules—one root element, matching closing tags, quoted attribute values, correct nesting—so any parser can read it.', topicIds: ['sia1-data-representation'] },
  { id: 'term-json-schema', term: 'JSON Schema', definition: 'A JSON document that describes and validates the structure, types, and constraints of other JSON documents.', topicIds: ['sia1-data-representation'] },
  { id: 'term-web-service', term: 'Web Service', definition: 'A software system supporting interoperable machine-to-machine interaction over standard internet technologies.', topicIds: ['sia1-web-services'] },
  { id: 'term-soap', term: 'SOAP', definition: 'A messaging framework specifying XML message format, message processing, and transport, mainly over HTTP.', topicIds: ['sia1-web-services'] },
  { id: 'term-wsdl', term: 'WSDL', definition: 'Web Services Description Language. An XML grammar describing network services as collections of endpoints that exchange messages.', topicIds: ['sia1-web-services'] },
  { id: 'term-uddi', term: 'UDDI', definition: 'Universal Description, Discovery, and Integration. A searchable repository of web service descriptions.', topicIds: ['sia1-web-services'] },
  { id: 'term-rpc', term: 'Remote Procedure Call', definition: 'Calling a procedure on a remote node through a local proxy that marshals parameters, so the caller barely notices the call was remote.', topicIds: ['sia1-web-services'] },
  { id: 'term-eai', term: 'EAI', definition: 'Enterprise Application Integration. Uniting the databases and workflows of business applications so data is used consistently across the enterprise.', topicIds: ['sia1-eai'] },
  { id: 'term-point-to-point', term: 'Point-to-Point Integration', definition: 'The earliest EAI model, in which a script extracts, reformats, and sends data between two applications.', topicIds: ['sia1-eai'] },
  { id: 'term-hub-spoke', term: 'Hub-and-Spoke Integration', definition: 'An EAI model where a centralised hub connects to applications, captures and reformats data, and decides where it is distributed.', topicIds: ['sia1-eai'] },
  { id: 'term-message-broker', term: 'Message Broker', definition: 'Integration software that extracts information from one application, converts it to the target format, and transmits it.', topicIds: ['sia1-eai'] },
  { id: 'term-middleware', term: 'Middleware', definition: 'Software between application programs and the operating system that supplies distributed computing capabilities and interfaces to them.', topicIds: ['sia1-middleware'] },
  { id: 'term-mom', term: 'MOM', definition: 'Message-Oriented Middleware. Infrastructure supporting the sending and receiving of messages between distributed systems.', topicIds: ['sia1-middleware'] },
  { id: 'term-pubsub', term: 'Publish/Subscribe', definition: 'A messaging pattern where publishers classify messages without knowing the subscribers that will receive them.', topicIds: ['sia1-middleware'] },
  { id: 'term-connection-pool', term: 'Connection Pool', definition: 'A reusable set of open connections middleware keeps for fast, efficient access to a back-end resource.', topicIds: ['sia1-middleware'] },
  { id: 'term-cloud', term: 'Cloud Computing', definition: 'On-demand network access to a shared pool of configurable computing resources, rapidly provisioned and released with minimal management effort.', topicIds: ['sia1-cloud'] },
  { id: 'term-iaas', term: 'IaaS', definition: 'Infrastructure as a Service. Compute, storage, and networking resources the customer configures.', topicIds: ['sia1-cloud'] },
  { id: 'term-paas', term: 'PaaS', definition: 'Platform as a Service. A managed platform on which customers build and run their own applications.', topicIds: ['sia1-cloud'] },
  { id: 'term-saas', term: 'SaaS', definition: 'Software as a Service. Finished applications delivered over the internet, such as web-based email.', topicIds: ['sia1-cloud'] },
  { id: 'term-hybrid-cloud', term: 'Hybrid Cloud', definition: 'A mix of public and private cloud where critical activities run privately and non-critical activities run publicly.', topicIds: ['sia1-cloud'] },
  { id: 'term-multi-tenancy', term: 'Multi-Tenancy', definition: 'A provider hosting many customers on the same infrastructure at the same time.', topicIds: ['sia1-cloud'] },
];

/** Default spaced-repetition state applied to every card before the first review. */
const NEW_CARD = {
  easeFactor: 2.5,
  interval: 0,
  repetitions: 0,
  nextReview: 0,
  masteryLevel: 'new',
} as const;

export const flashcards: Flashcard[] = [
  { id: 'fc-sia1-01', topicId: 'sia1-eia', front: 'What is the primary goal of an Enterprise Information Architecture?', back: 'To reduce complexity, and thereby remove the factors that inhibit change and block new business paradigms.', tags: ['eia'], ...NEW_CARD },
  { id: 'fc-sia1-02', topicId: 'sia1-eia', front: 'Which four EA methodologies account for most of the field?', back: 'TOGAF, the Zachman Framework, the Federal Enterprise Architecture, and the Gartner methodology.', tags: ['eia'], ...NEW_CARD },
  { id: 'fc-sia1-03', topicId: 'sia1-eia', front: 'Is the scope of EIA every piece of information in the enterprise?', back: 'No. In practice EIA focuses on information assets with enterprise significance that are needed to achieve effective business change.', tags: ['eia'], ...NEW_CARD },
  { id: 'fc-sia1-04', topicId: 'sia1-governance', front: 'Which two issues does IT governance exist to address?', back: 'That IT delivers value to the business, and that IT-related risks are managed.', tags: ['governance'], ...NEW_CARD },
  { id: 'fc-sia1-05', topicId: 'sia1-governance', front: 'Name the four risk treatments.', back: 'Avoid, mitigate, transfer, and accept.', tags: ['governance', 'risk'], ...NEW_CARD },
  { id: 'fc-sia1-06', topicId: 'sia1-governance', front: 'Which three duties should be segregated?', back: 'Custody of the assets, authorisation, and recording of transactions.', tags: ['governance', 'controls'], ...NEW_CARD },
  { id: 'fc-sia1-07', topicId: 'sia1-data-modelling', front: 'What is the difference between data and information?', back: 'Information is data in context; data has the same value and meaning regardless of the context in which it is used.', tags: ['modelling'], ...NEW_CARD },
  { id: 'fc-sia1-08', topicId: 'sia1-data-modelling', front: 'Which question does each modelling layer answer?', back: 'Conceptual asks what, logical asks how, and physical asks where.', tags: ['modelling'], ...NEW_CARD },
  { id: 'fc-sia1-09', topicId: 'sia1-soa', front: 'Which SOA principle says a service must not keep data between requests?', back: 'Service statelessness — that responsibility belongs to the client application.', tags: ['soa'], ...NEW_CARD },
  { id: 'fc-sia1-10', topicId: 'sia1-soa', front: 'Name the three SOA participants involved in discovery.', back: 'The service provider, the service registry (broker or repository), and the service consumer.', tags: ['soa'], ...NEW_CARD },
  { id: 'fc-sia1-11', topicId: 'sia1-soa', front: 'What are the five horizontal layers of the SOA framework?', back: 'Consumer interface, business process, services, service component, and operational systems.', tags: ['soa'], ...NEW_CARD },
  { id: 'fc-sia1-12', topicId: 'sia1-microservices', front: 'What is the deployment advantage of microservices?', back: 'Only the service that changed needs to be deployed, and only the component under load needs to be scaled.', tags: ['microservices'], ...NEW_CARD },
  { id: 'fc-sia1-13', topicId: 'sia1-microservices', front: 'Which component handles requests coming from many different clients?', back: 'The API gateway.', tags: ['microservices'], ...NEW_CARD },
  { id: 'fc-sia1-14', topicId: 'sia1-data-representation', front: 'List the five rules for well-formed XML.', back: 'One root element, a closing tag for every element, case-sensitive tags, properly nested elements, and quoted attribute values.', tags: ['xml'], ...NEW_CARD },
  { id: 'fc-sia1-15', topicId: 'sia1-data-representation', front: 'What are the seven JSON values?', back: 'Object, array, number, string, true, false, and null.', tags: ['json'], ...NEW_CARD },
  { id: 'fc-sia1-16', topicId: 'sia1-data-representation', front: 'Why must JSON object keys be unique?', back: 'Parser behaviour on duplicate keys is unpredictable; many implementations report only the last name/value pair.', tags: ['json'], ...NEW_CARD },
  { id: 'fc-sia1-17', topicId: 'sia1-web-services', front: 'What are the two child elements of a SOAP envelope?', back: 'An optional Header and a mandatory Body.', tags: ['soap'], ...NEW_CARD },
  { id: 'fc-sia1-18', topicId: 'sia1-web-services', front: 'What must a SOAP node do with a header block targeted at its role?', back: 'Perform the processing the block implies, then delete the header block before relaying the message onward.', tags: ['soap'], ...NEW_CARD },
  { id: 'fc-sia1-19', topicId: 'sia1-web-services', front: 'Which WSDL element attaches a concrete protocol and data format to a port type?', back: 'The binding.', tags: ['wsdl'], ...NEW_CARD },
  { id: 'fc-sia1-20', topicId: 'sia1-eai', front: 'Why does point-to-point integration stop scaling?', back: 'Every new application adds dependencies that must be programmed and maintained, so the connections become unmanageable.', tags: ['eai'], ...NEW_CARD },
  { id: 'fc-sia1-21', topicId: 'sia1-eai', front: 'Which EAI type is cheapest, and why?', back: 'Data-level EAI, because application code is not changed, so there is no need to test and deploy the applications.', tags: ['eai'], ...NEW_CARD },
  { id: 'fc-sia1-22', topicId: 'sia1-middleware', front: 'Where exactly does middleware sit?', back: 'Between the application programs and the operating system and base networking — between front-end requests and back-end resources.', tags: ['middleware'], ...NEW_CARD },
  { id: 'fc-sia1-23', topicId: 'sia1-middleware', front: 'How does asynchronous messaging improve fault tolerance?', back: 'Messages are held in a queue by the middleware until the receiver recovers, so nothing is lost while it is down.', tags: ['middleware'], ...NEW_CARD },
  { id: 'fc-sia1-24', topicId: 'sia1-cloud', front: 'Name the five essential characteristics of cloud computing.', back: 'On-demand self-service, broad network access, resource pooling, rapid elasticity, and measured service.', tags: ['cloud'], ...NEW_CARD },
  { id: 'fc-sia1-25', topicId: 'sia1-cloud', front: 'Name the four cloud deployment models.', back: 'Public, private, community, and hybrid.', tags: ['cloud'], ...NEW_CARD },
  { id: 'fc-sia1-26', topicId: 'sia1-cloud', front: 'Name the five cloud actors.', back: 'Cloud consumer, cloud provider, cloud auditor, cloud broker, and cloud carrier.', tags: ['cloud'], ...NEW_CARD },
];

export const questions: Question[] = [
  {
    id: 'q-sia1-01',
    topicId: 'sia1-eia',
    difficulty: 2,
    type: 'mcq',
    stem: 'Why do large enterprises adopt an Enterprise Service Bus (ESB)?',
    options: [
      'To completely eliminate the need for databases.',
      'To provide centralised routing, translation, and communication between systems.',
      'To replace HTML frontends with React.',
      'To increase the coupling between individual services.',
    ],
    correct: [1],
    explanation: 'An ESB acts as shared infrastructure that handles routing, protocol translation, and data transformation, replacing the tight coupling of point-to-point connections.',
    adaptiveWeight: 1.0,
  },
  {
    id: 'q-sia1-02',
    topicId: 'sia1-eia',
    difficulty: 3,
    type: 'mcq',
    stem: 'Which statement best describes the practical scope of Enterprise Information Architecture?',
    options: [
      'Every byte of data stored anywhere in the enterprise.',
      'Only the data held in the data warehouse.',
      'Information assets with enterprise significance that are needed to achieve effective business change.',
      'Only unstructured content such as documents and images.',
    ],
    correct: [2],
    explanation: 'Although "all enterprise information" is true at an abstract level, EIA in practice focuses on enterprise-significant assets needed for effective business change.',
    adaptiveWeight: 1.5,
  },
  {
    id: 'q-sia1-03',
    topicId: 'sia1-governance',
    difficulty: 3,
    type: 'scenario',
    stem: 'One employee creates a vendor record, approves that vendor\'s invoices, and reconciles the payments. What is the clearest control weakness?',
    options: [
      'Insufficient metadata management.',
      'Poor segregation of duties.',
      'Missing data warehouse.',
      'Excessive strategic planning.',
    ],
    correct: [1],
    explanation: 'Authorisation, custody, and recording are concentrated in one person, so errors or irregularities can go undetected. Where separation is impractical, compensating controls such as audit trails and independent review are required.',
    adaptiveWeight: 2.0,
  },
  {
    id: 'q-sia1-04',
    topicId: 'sia1-governance',
    difficulty: 2,
    type: 'mcq',
    stem: 'A company buys cyber insurance to cover part of the financial impact of a breach. Which risk treatment is this?',
    options: ['Avoid', 'Mitigate', 'Transfer', 'Accept'],
    correct: [2],
    explanation: 'Insurance shifts part of the financial consequence to another party, which is risk transfer. Mitigation would reduce likelihood or impact directly.',
    adaptiveWeight: 1.0,
  },
  {
    id: 'q-sia1-05',
    topicId: 'sia1-data-modelling',
    difficulty: 3,
    type: 'scenario',
    stem: 'Marketing and customer support each need a different view of the same Customer for their own processes. Which modelling layer are they working in?',
    options: ['Conceptual', 'Logical', 'Physical', 'Operational'],
    correct: [1],
    explanation: 'Information Views refine a shared information concept for a particular process or audience, which places them in the logical layer.',
    adaptiveWeight: 1.5,
  },
  {
    id: 'q-sia1-06',
    topicId: 'sia1-soa',
    difficulty: 3,
    type: 'scenario',
    stem: 'A service stores each caller\'s progress internally, so a second instance cannot continue serving that caller. Which SOA principle has been violated?',
    options: [
      'Service discoverability',
      'Standardised service contract',
      'Service statelessness',
      'Service composability',
    ],
    correct: [2],
    explanation: 'Statelessness requires that services not keep data from one state to the next; retaining conversation state must be done by the client application.',
    adaptiveWeight: 1.5,
  },
  {
    id: 'q-sia1-07',
    topicId: 'sia1-microservices',
    difficulty: 4,
    type: 'scenario',
    stem: 'A company has a massive e-commerce monolith. Billing and shipping currently query the same "Orders" SQL table directly. What should they do under a microservices model?',
    options: [
      'Keep the shared database, but put an API in front of it.',
      'Split the data by service boundary and request across boundaries through APIs.',
      'Use an ESB to sync the shared database to a cloud instance.',
      'Convert the SQL database to NoSQL.',
    ],
    correct: [1],
    explanation: 'Microservices are bounded by contexts: each service encapsulates its own domain and defines integration with others explicitly, so shipping calls the billing service rather than reading its tables.',
    adaptiveWeight: 2.5,
  },
  {
    id: 'q-sia1-08',
    topicId: 'sia1-data-representation',
    difficulty: 2,
    type: 'mcq',
    stem: 'A JSON object contains the key "Title" twice with different values. What should you expect?',
    options: [
      'Both values are always returned as an array.',
      'Parser behaviour is unpredictable; many implementations keep only the last pair.',
      'The document fails XML Schema validation.',
      'The first pair is always kept.',
    ],
    correct: [1],
    explanation: 'When names within a JSON object are not unique, the behaviour of receiving software is unpredictable — some report the last pair, some error, some report all of them.',
    adaptiveWeight: 1.5,
  },
  {
    id: 'q-sia1-09',
    topicId: 'sia1-data-representation',
    difficulty: 2,
    type: 'mcq',
    stem: 'A developer needs a line break inside a JSON string value. What is the correct approach?',
    options: [
      'Press Enter inside the quotes to continue on the next line.',
      'Wrap the value in a CDATA section.',
      'Use the \\n escape sequence.',
      'Add a // comment marking the break.',
    ],
    correct: [2],
    explanation: 'JSON forbids multi-line strings, so a newline is written as the two-symbol escape \\n and converted by the parser. JSON also has no comment syntax.',
    adaptiveWeight: 1.0,
  },
  {
    id: 'q-sia1-10',
    topicId: 'sia1-web-services',
    difficulty: 3,
    type: 'scenario',
    stem: 'An intermediary node must authenticate a message and then pass it along the SOAP path. Where does that instruction belong?',
    options: [
      'In a header block targeted at that node\'s SOAP role.',
      'In the SOAP body next to the payload.',
      'In the WSDL binding element.',
      'In the UDDI registry entry.',
    ],
    correct: [0],
    explanation: 'Header blocks control processing and are targeted at a SOAP role. The node in that role performs the implied processing and deletes the block before relaying the message.',
    adaptiveWeight: 2.0,
  },
  {
    id: 'q-sia1-11',
    topicId: 'sia1-web-services',
    difficulty: 3,
    type: 'mcq',
    stem: 'A team wants to offer the same operations over an additional protocol without redefining them. Which WSDL element changes?',
    options: ['Types', 'Message', 'Port type', 'Binding'],
    correct: [3],
    explanation: 'The binding attaches a concrete protocol and data format to an existing abstract port type, which is precisely why WSDL separates abstract from concrete definitions.',
    adaptiveWeight: 1.5,
  },
  {
    id: 'q-sia1-12',
    topicId: 'sia1-eai',
    difficulty: 3,
    type: 'scenario',
    stem: 'A mainframe application exposes no database or business-process access, so architects drive it through its screens. Which EAI type is this?',
    options: [
      'Data-level EAI',
      'Application interface level EAI',
      'Method level EAI',
      'User interface level EAI',
    ],
    correct: [3],
    explanation: 'User interface level EAI is the most primitive approach and is used only when the application offers no other point of integration.',
    adaptiveWeight: 1.5,
  },
  {
    id: 'q-sia1-13',
    topicId: 'sia1-middleware',
    difficulty: 2,
    type: 'mcq',
    stem: 'A payment flow must move safely from one phase to the next under transaction process monitoring. Which middleware type fits?',
    options: [
      'Content-centric middleware',
      'Transactional middleware',
      'Embedded middleware',
      'Database middleware',
    ],
    correct: [1],
    explanation: 'Transactional middleware ensures transactions move from one phase to the next through transaction process monitoring.',
    adaptiveWeight: 1.0,
  },
  {
    id: 'q-sia1-14',
    topicId: 'sia1-cloud',
    difficulty: 2,
    type: 'scenario',
    stem: 'Several state agencies share cloud infrastructure because they have the same mission and security requirements. Which deployment model is this?',
    options: ['Public cloud', 'Private cloud', 'Community cloud', 'Hybrid cloud'],
    correct: [2],
    explanation: 'A community cloud is shared among organisations with similar interests and requirements such as mission, security requirements, or policy.',
    adaptiveWeight: 1.0,
  },
  {
    id: 'q-sia1-15',
    topicId: 'sia1-cloud',
    difficulty: 3,
    type: 'mcq',
    stem: 'Which cloud actor provides connectivity and transport of cloud services from providers to consumers?',
    options: ['Cloud broker', 'Cloud auditor', 'Cloud carrier', 'Cloud provider'],
    correct: [2],
    explanation: 'The cloud carrier is the intermediary that provides connectivity and transport. A broker is an intermediary in the purchase, and an auditor independently assesses performance and security.',
    adaptiveWeight: 1.5,
  },
];
